### ISSUE TITLE
Unable to create a graph

### ISSUE THREAD

**Issue by aaristov** [BaroudLab/Griottes#1]
Hi Gustave,

I was checking your library, hoping to create a napari plugin. Below are the steps I went through before stubling at the error:
1. I open test image in napari (cells3D) 
![image](https://user-images.githubusercontent.com/11408456/159359305-d82d45a1-3910-439a-8f26-9234bcb6250c.png)
2. I segmented the nuclei and created a labelled mask 
![image](https://user-images.githubusercontent.com/11408456/159359442-c2dfe055-fd88-423a-883f-f25922f795e0.png)
3. I loaded this labels into jupyter: 
![image](https://user-images.githubusercontent.com/11408456/159359702-4b51c87a-4e47-4156-8dcd-9bec37ccffa9.png)
4. And finally I tried to create a graph using the command from the tutorial `
G = graph_generation_func.generate_contact_graph(labels)`
The error I've got:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-15-44149e326267> in <module>
----> 1 G = graph_generation_func.generate_contact_graph(labels)

~/miniconda3/envs/nd2/lib/python3.8/site-packages/griottes/graphmaker/graph_generation_func.py in generate_contact_graph(user_entry, mask_channel, min_area, analyze_fluo_channels, fluo_channel_analysis_method, radius, descriptors)
    540     if isinstance(user_entry, np.ndarray):
    541 
--> 542         user_entry = create_region_contact_frame(
    543             user_entry,
    544             flat_image=True,

~/miniconda3/envs/nd2/lib/python3.8/site-packages/griottes/graphmaker/graph_generation_func.py in create_region_contact_frame(label_img, mask_channel, flat_image, min_area, analyze_fluo_channels, fluo_channel_analysis_method, radius)
    468         edge_frame = get_region_contacts(label_img[..., mask_channel])
    469     else:
--> 470         edge_frame = get_region_contacts(label_img)
    471 
    472     # get the region properties

~/miniconda3/envs/nd2/lib/python3.8/site-packages/griottes/graphmaker/graph_generation_func.py in get_region_contacts(mask_image)
    411     """
    412 
--> 413     assert np.ndim(mask_image) == 2
    414 
    415     # final output

AssertionError: 
```
Why doesn't it work with 3D labels???

Thanks in advance!

**Comment by gronteix** [comment]
For the moment the contact graph hasn't been adapted in 3D, for the reason that the "contact" option makes sense if you're using the membranes to delimit the cells and that the 3D volumes are usually ill-defined (i.e. we had this issue on the light sheet microscope). This is specified in the preprint.

However, if you use the Delaunay graph generation function then it should be fine in 3D.

Action point: adapt the function for contact-based graph generation for 3D images.
