### ISSUE TITLE
Issue with generating Figure_4.ipynb figure

### ISSUE THREAD

**Issue by burcu-ayoglu** [BaroudLab/Griottes#10]
Hi, I was trying to run Figure_4.ipynb, I managed to get all variables but at the end I'm not able to plot. Is it possible for you to check the final plotting function?
![Screen Shot 2022-04-19 at 14 49 30](https://user-images.githubusercontent.com/36070978/164008282-4ff67591-62c7-4d46-a21d-6ae66652841d.png)
?

**Comment by aaristov** [comment]
I can't reproduce your issue with the current version. Could you please run `pip freeze|grep griottes` and post the output?

**Comment by burcu-ayoglu** [comment]
griottes==0.0.3

You mean this?

**Comment by gronteix** [comment]
Hi! I think there is a descrepancy between the version you might be working on and the current update (there's quite a lot of work going on updating the examples - sorry for that). You can try downloading the latest version of griottes it should work now (I also tested the example to check on @aaristov's comment).

**Comment by gronteix** [comment]
This can be done by going to the repository on your terminal and typing `git pull` :)

**Comment by burcu-ayoglu** [comment]
Yes, it works now, I could generate the figures in Example 4 file. Thanks! I will give it a try with my own csv file, let's see if I'll manage
